name: Teste de atualização rápida

on:
  workflow_dispatch:  # Só roda manualmente

jobs:
  update_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 asyncpg

      - name: Rodar script de teste
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          python scripts/update_data_test.py
